name: wdoi_dev

services:

  elastic_dev: 
    image: elasticsearch:8.13.0
    restart: unless-stopped
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g" 

  qdrant_dev:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qddata:/qdrant/storage
    environment:
      - QDRANT__TELEMETRY_DISABLED=True

  cross_encoder_dev:
    build: ./backend/cross-encoder-reranker-service
    restart: unless-stopped
    ports:
      - "8300:8300"
    environment:
      NUM_THREADS: 4

  dense_embed_dev:
    build: ./backend/dense-embedding-service
    restart: unless-stopped
    ports:
      - "8100:8100"
    environment:
      NUM_THREADS: 4

  sparse_embed_dev:
    build: ./backend/sparse-embedding-service
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      NUM_THREADS: 2
      ACCESS_TOKEN: 

volumes:
  esdata:
    driver: local
  qddata:
    driver: local