name: wdoi_dev

services:

  elastic_dev:
    image: elasticsearch:8.13.0
    restart: unless-stopped
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata:
    driver: local